import { StyleSheet } from "react-native";
import { palette } from "./colors";

export const ui = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: palette.bg,
  },
  page: {
    padding: 20,
    justifyContent: "center",
  },
  card: {
    backgroundColor: palette.card,
    borderRadius: 24,
    padding: 24,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.5)",
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: palette.ink,
    marginBottom: 8,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 14,
    color: palette.muted,
    marginBottom: 24,
    lineHeight: 20,
    textAlign: "center",
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.inputBg,
    borderWidth: 1,
    borderColor: palette.line,
    borderRadius: 12,
    marginBottom: 16,
    paddingHorizontal: 16,
    height: 52,
  },
  input: {
    flex: 1,
    height: "100%",
    fontSize: 16,
    color: palette.ink,
    marginLeft: 12,
  },
  buttonContainer: {
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
    shadowColor: palette.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  button: {
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  buttonGhost: {
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    marginBottom: 16,
  },
  buttonText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 16,
  },
  buttonGhostText: {
    color: palette.primary,
    fontWeight: "600",
    fontSize: 14,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: palette.ink,
    marginBottom: 12,
  },
  muted: {
    color: palette.muted,
  },
  avatarSm: {
    width: 42,
    height: 42,
    borderRadius: 999,
    marginRight: 10,
    backgroundColor: palette.gradient.blueLight,
  },
  avatarLg: {
    width: 90,
    height: 90,
    borderRadius: 999,
    marginRight: 12,
    backgroundColor: palette.gradient.blueLight,
  },
  tag: {
    alignSelf: "flex-start",
    borderRadius: 999,
    backgroundColor: palette.gradient.purpleLight,
    paddingHorizontal: 12,
    paddingVertical: 6,
    color: palette.primary,
    marginVertical: 8,
    fontWeight: "600",
    fontSize: 12,
  },
});
